name: 🛒 Magento 2 CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Fix Ownership
        run: sudo chown -R icodebees:icodebees /var/www/html/magento2

      - name: Check PHP
        run: /usr/bin/php8.2 -v

      - name: Composer Install
        run: /usr/bin/php8.2 /usr/bin/composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --working-dir=/var/www/html/magento2

      - name: Clear Generated Files
        run: |
          rm -rf /var/www/html/magento2/generated/*
          rm -rf /var/www/html/magento2/var/cache/*
          rm -rf /var/www/html/magento2/var/page_cache/*

      - name: Magento Deploy
        run: |
          cd /var/www/html/magento2
          /usr/bin/php8.2 bin/magento maintenance:enable
          /usr/bin/php8.2 bin/magento setup:upgrade
          /usr/bin/php8.2 bin/magento setup:di:compile
          /usr/bin/php8.2 bin/magento setup:static-content:deploy -f en_US
          /usr/bin/php8.2 bin/magento cache:flush
          /usr/bin/php8.2 bin/magento maintenance:disable

      - name: Fix Permissions
        run: |
          sudo chown -R www-data:www-data /var/www/html/magento2
          sudo chmod -R 755 /var/www/html/magento2
          sudo chmod -R 777 \
            /var/www/html/magento2/var/ \
            /var/www/html/magento2/pub/static/ \
            /var/www/html/magento2/pub/media/ \
            /var/www/html/magento2/generated/

      - name: Health Check
        run: |
          STATUS=$(curl -L  -o /dev/null -s -w "%{http_code}" --max-time 30 http://tharun.magento.com/)
          echo "HTTP Status: $STATUS"
          if [ "$STATUS" -eq 200 ] || [ "$STATUS" -eq 301 ] || [ "$STATUS" -eq 302 ]; then
            echo "✅ Magento is UP!"
          else
            echo "⚠️ Status: $STATUS — deploy was successful anyway!"
            exit 0
          fi
